# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Emoji-Dash' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'pop', '~> 1.0'
  # Pods for Emoji-Dash

  target 'Emoji-DashTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
